<?php

namespace admin\components;

use yii;

class UrlRule extends \yii\rest\UrlRule
{
    public function init()
    {
        foreach(Yii::$app->getModule('admin')->controllerMap as $alias => $className) {
            $class = sprintf('%s/%s', 'admin', $alias);
            $this->controller[] = $class;
        }
        parent::init();
    }

    /* public $controller = ["admin/api-user", "admin/api-menu", "admin/api-group"]; // generated by bootstrap modulescontrollermaps */

    public $pluralize = false;
}
