<?php

namespace admin\components;

use yii;

class UrlRule extends \yii\rest\UrlRule
{
    public function init()
    {
        foreach (yii::$app->params['apis'] as $item) {
            $class = sprintf('%s/%s', 'admin', $item['alias']);
            $this->controller[] = $class;
        }
        parent::init();
    }

    /* public $controller = ["admin/api-user", "admin/api-menu", "admin/api-group"]; // generated by bootstrap modulescontrollermaps */

    public $pluralize = false;
}
