<?php

namespace luya\admin\components;

use yii;

/**
 * Url rule for NgRest Apis
 *
 * @author Basil Suter <basil@nadar.io>
 */
class UrlRule extends \yii\rest\UrlRule
{
    public function init()
    {
        $map = Yii::$app->getModule('admin')->controllerMap;

        if (count($map) > 0) {
            foreach ($map as $alias => $className) {
                $class = sprintf('%s/%s', 'admin', $alias);
                $this->controller[] = $class;
            }

            parent::init();
        } else {
            $this->controller = [];
        }
    }

    /* public $controller = ["admin/api-user", "admin/api-menu", "admin/api-group"]; // generated by bootstrap modulescontrollermaps */

    public $pluralize = false;
}
