<?php

return
    array(
            43 =>
            array(
                    'id' => '43',
                    'nav_id' => '1',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/home',
                    'title' => 'Homepage',
                    'alias' => 'home',
                    'description' => '',
                    'keywords' => null,
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1457091369',
                    'timestamp_update' => '1483367249',
                    'is_home' => '1',
                    'parent_nav_id' => '0',
                    'sort_index' => '1',
                    'is_hidden' => '1',
                    'type' => '1',
                    'nav_item_type_id' => '42',
                    'redirect' => false,
                    'module_name' => false,
                    'container' => 'default',
                    'depth' => 1,
            ),
            103 =>
            array(
                    'id' => '103',
                    'nav_id' => '2',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/produit',
                    'title' => 'Produit',
                    'alias' => 'produit',
                    'description' => null,
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483337217',
                    'timestamp_update' => '1483365086',
                    'is_home' => '0',
                    'parent_nav_id' => '0',
                    'sort_index' => '2',
                    'is_hidden' => '0',
                    'type' => '1',
                    'nav_item_type_id' => '65',
                    'redirect' => false,
                    'module_name' => false,
                    'container' => 'default',
                    'depth' => 1,
            ),
            108 =>
            array(
                    'id' => '108',
                    'nav_id' => '6',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/carte',
                    'title' => 'Carte',
                    'alias' => 'carte',
                    'description' => 'Hier werden sie über Verkaufs- und Rückgabestellen informiert',
                    'keywords' => 'Sammelstelle, Recycling-Sack, Recycling, Sack, Getränkekarton, finden, suchen, Karte, Kunststoff, Kunststoff-Flasche, nächste, Bern, Basel, Zürich, Genf, Lausanne, Zug, St. Gallen, Abfall, abgeben, zurück geben, voll, 35 Liter, Rückgabestelle, Rückgabe, Verkaufsstelle, Verkauf, Stelle',
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483342814',
                    'timestamp_update' => '1483344418',
                    'is_home' => '0',
                    'parent_nav_id' => '0',
                    'sort_index' => '3',
                    'is_hidden' => '0',
                    'type' => '1',
                    'nav_item_type_id' => '70',
                    'redirect' => false,
                    'module_name' => false,
                    'container' => 'default',
                    'depth' => 1,
            ),
            111 =>
            array(
                    'id' => '111',
                    'nav_id' => '40',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/processus-de-recyclage',
                    'title' => 'Processus de recyclage',
                    'alias' => 'processus-de-recyclage',
                    'description' => 'Le processus de recyclage est expliqué en images. Utilisez les touches fléchées à droite pour passer entre les différentes étapes du processus.',
                    'keywords' => 'Le processus de recyclage est expliqué en images. Utilisez les touches fléchées à droite pour passer entre les différentes étapes du processus.',
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483345175',
                    'timestamp_update' => '1483365176',
                    'is_home' => '0',
                    'parent_nav_id' => '0',
                    'sort_index' => '4',
                    'is_hidden' => '0',
                    'type' => '1',
                    'nav_item_type_id' => '73',
                    'redirect' => false,
                    'module_name' => false,
                    'container' => 'default',
                    'depth' => 1,
            ),
            112 =>
            array(
                    'id' => '112',
                    'nav_id' => '22',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/partenaires-de-collecte-de-logistique',
                    'title' => 'Partenaires de collecte / de logistique',
                    'alias' => 'partenaires-de-collecte-de-logistique',
                    'description' => null,
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483347229',
                    'timestamp_update' => '1483366992',
                    'is_home' => '0',
                    'parent_nav_id' => '0',
                    'sort_index' => '5',
                    'is_hidden' => '0',
                    'type' => '1',
                    'nav_item_type_id' => '74',
                    'redirect' => false,
                    'module_name' => false,
                    'container' => 'default',
                    'depth' => 1,
            ),
            119 =>
            array(
                    'id' => '119',
                    'nav_id' => '24',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/savoir',
                    'title' => 'Savoir',
                    'alias' => 'savoir',
                    'description' => null,
                    'keywords' => 'Wissen, Recycling, Recycling-Sack, Sack, Umfeld, Downloads, Glossar, Links, Themengebiet',
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483353054',
                    'timestamp_update' => '1483353221',
                    'is_home' => '0',
                    'parent_nav_id' => '0',
                    'sort_index' => '6',
                    'is_hidden' => '0',
                    'type' => '1',
                    'nav_item_type_id' => '81',
                    'redirect' => false,
                    'module_name' => false,
                    'container' => 'default',
                    'depth' => 1,
            ),
            122 =>
            array(
                    'id' => '122',
                    'nav_id' => '13',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/a-notre-sujet',
                    'title' => 'A notre sujet',
                    'alias' => 'a-notre-sujet',
                    'description' => 'Ici vous trouvez plus des informations sur l’association «CI Sac de Recyclage». L\'association, fondée le 17 décembre 2015, a son siège à Bâle et elle gère ce système de collecte.',
                    'keywords' => 'Ici vous trouvez plus des informations sur l’association «CI Sac de Recyclage». L\'association, fondée le 17 décembre 2015, a son siège à Bâle et elle gère ce système de collecte.',
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483354802',
                    'timestamp_update' => '1483366887',
                    'is_home' => '0',
                    'parent_nav_id' => '0',
                    'sort_index' => '7',
                    'is_hidden' => '0',
                    'type' => '1',
                    'nav_item_type_id' => '84',
                    'redirect' => false,
                    'module_name' => false,
                    'container' => 'default',
                    'depth' => 1,
            ),
            86 =>
            array(
                    'id' => '86',
                    'nav_id' => '81',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/aktuell-andere-sprachen',
                    'title' => 'Aktuell (andere Sprachen)',
                    'alias' => 'aktuell-andere-sprachen',
                    'description' => '',
                    'keywords' => '',
                    'create_user_id' => '2',
                    'update_user_id' => '2',
                    'timestamp_create' => '1461576245',
                    'timestamp_update' => '1461576256',
                    'is_home' => '0',
                    'parent_nav_id' => '0',
                    'sort_index' => '12',
                    'is_hidden' => '1',
                    'type' => '2',
                    'nav_item_type_id' => '7',
                    'redirect' => false,
                    'module_name' => 'rsnews',
                    'container' => 'default',
                    'depth' => 1,
            ),
            104 =>
            array(
                    'id' => '104',
                    'nav_id' => '43',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/produit/que-collecter',
                    'title' => 'Que collecter?',
                    'alias' => 'produit/que-collecter',
                    'description' => 'Erfahren Sie hier, was im «Recycling-Sack» gesammelt werden darf und was nicht.',
                    'keywords' => 'Was sammeln, Recycling-Sack, Recycling, Sack, Fremdstoffe, Zielstoffe, reingehören, Fremdstoffe, Getränkekarton, Kunststoff-Flaschen, Becher, Tiefziehfolie, Blister, Kanister, Tube, Tragtasche, Folie, Nachfüllbeutel, Spielzeug, Blumentopf, Schale',
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483337545',
                    'timestamp_update' => '1483360373',
                    'is_home' => '0',
                    'parent_nav_id' => '2',
                    'sort_index' => '5',
                    'is_hidden' => '0',
                    'type' => '1',
                    'nav_item_type_id' => '66',
                    'redirect' => false,
                    'module_name' => false,
                    'container' => 'default',
                    'depth' => 2,
            ),
            105 =>
            array(
                    'id' => '105',
                    'nav_id' => '44',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/produit/comment-collecter',
                    'title' => 'Comment collecter?',
                    'alias' => 'produit/comment-collecter',
                    'description' => 'Erfahren Sie hier, wie Sie mit der Sammlung zu Hause richtig umgehen.',
                    'keywords' => 'Deckel, was sammeln, zusammendrücken, Recycling-Sack, Sack, Recycling, Tipps, Umgang, Befüllung, zubinden, Sammelsack',
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483337795',
                    'timestamp_update' => '1483360733',
                    'is_home' => '0',
                    'parent_nav_id' => '2',
                    'sort_index' => '7',
                    'is_hidden' => '0',
                    'type' => '1',
                    'nav_item_type_id' => '67',
                    'redirect' => false,
                    'module_name' => false,
                    'container' => 'default',
                    'depth' => 2,
            ),
            106 =>
            array(
                    'id' => '106',
                    'nav_id' => '46',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/produit/pourquoi-collecter',
                    'title' => 'Pourquoi collecter?',
                    'alias' => 'produit/pourquoi-collecter',
                    'description' => 'Erfahren Sie hier, weshalb die kombinierte Sammlung mit dem «Recycling-Sack» Sinn macht.',
                    'keywords' => 'Gründe, Vorteile, Recycling-Sack, Recycling, Sack, wieso, sammeln, Sinn, sinnvoll, Umwelt, Vereinfachung',
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483338051',
                    'timestamp_update' => '1483338325',
                    'is_home' => '0',
                    'parent_nav_id' => '2',
                    'sort_index' => '9',
                    'is_hidden' => '0',
                    'type' => '1',
                    'nav_item_type_id' => '68',
                    'redirect' => false,
                    'module_name' => false,
                    'container' => 'default',
                    'depth' => 2,
            ),
            107 =>
            array(
                    'id' => '107',
                    'nav_id' => '45',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/produit/ou-vente-et-depot',
                    'title' => 'Où? Vente et dépôt',
                    'alias' => 'produit/ou-vente-et-depot',
                    'description' => 'Erfahren Sie hier weitere Informationen zu Verkaufs- und Rückgabestellen des «Recycling-Sacks»',
                    'keywords' => 'Sammelstelle, Recycling-Sack, Recycling, Sack, Getränkekarton, finden, suchen, Karte, Kunststoff, Kunststoff-Flasche, nächste, Abfall, abgeben, zurück geben, voll, 35 Liter, Rückgabestelle, Rückgabe, Verkaufsstelle, Verkauf, Stelle',
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483338374',
                    'timestamp_update' => '1483360755',
                    'is_home' => '0',
                    'parent_nav_id' => '2',
                    'sort_index' => '10',
                    'is_hidden' => '0',
                    'type' => '1',
                    'nav_item_type_id' => '69',
                    'redirect' => false,
                    'module_name' => false,
                    'container' => 'default',
                    'depth' => 2,
            ),
            110 =>
            array(
                    'id' => '110',
                    'nav_id' => '91',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/produit/la-differance-avec-des-collectes-de-plastiques-melanges',
                    'title' => 'La differance avec des collectes de plastiques mélangés',
                    'alias' => 'produit/la-differance-avec-des-collectes-de-plastiques-melanges',
                    'description' => 'Le «sac de recyclage» se distingue clairement des collectes de plastiques mélangés.',
                    'keywords' => 'Le «sac de recyclage» se distingue clairement des collectes de plastiques mélangés.',
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483343688',
                    'timestamp_update' => '1483365143',
                    'is_home' => '0',
                    'parent_nav_id' => '2',
                    'sort_index' => '17',
                    'is_hidden' => '0',
                    'type' => '1',
                    'nav_item_type_id' => '72',
                    'redirect' => false,
                    'module_name' => false,
                    'container' => 'default',
                    'depth' => 2,
            ),
            109 =>
            array(
                    'id' => '109',
                    'nav_id' => '34',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/produit/faq-questions-frequentes',
                    'title' => 'FAQ – Questions fréquentes',
                    'alias' => 'produit/faq-questions-frequentes',
                    'description' => 'Erhalten Sie hier Antworten zu häufig gestellten Fragen.',
                    'keywords' => 'FAQ, häufig, gestellte, Fragen, häufig gestellte Fragen, Recycling, Recycling-Sack, Sack, Fragen, Antworten',
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483342973',
                    'timestamp_update' => '1483343538',
                    'is_home' => '0',
                    'parent_nav_id' => '2',
                    'sort_index' => '18',
                    'is_hidden' => '0',
                    'type' => '1',
                    'nav_item_type_id' => '71',
                    'redirect' => false,
                    'module_name' => false,
                    'container' => 'default',
                    'depth' => 2,
            ),
            123 =>
            array(
                    'id' => '123',
                    'nav_id' => '14',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/a-notre-sujet/contact',
                    'title' => 'Contact',
                    'alias' => 'a-notre-sujet/contact',
                    'description' => 'Treten Sie mit uns über diese Formular in Kontakt.',
                    'keywords' => 'Kontakt, Formular, Recycling-Sack, Recycling, Sack',
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483355016',
                    'timestamp_update' => '1483355038',
                    'is_home' => '0',
                    'parent_nav_id' => '13',
                    'sort_index' => '1',
                    'is_hidden' => '0',
                    'type' => '1',
                    'nav_item_type_id' => '85',
                    'redirect' => false,
                    'module_name' => false,
                    'container' => 'default',
                    'depth' => 2,
            ),
            124 =>
            array(
                    'id' => '124',
                    'nav_id' => '18',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/a-notre-sujet/lassociation',
                    'title' => 'L’association',
                    'alias' => 'a-notre-sujet/lassociation',
                    'description' => 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem.',
                    'keywords' => 'Über uns, Recycling, Sack, Recycling-Sack, Organisation, Verein, IG, Interessengemeinschaft, Müller Recycling AG, Redilo GmbH, Geschäftsführer, Präsident, Sitz',
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483355062',
                    'timestamp_update' => '1483366567',
                    'is_home' => '0',
                    'parent_nav_id' => '13',
                    'sort_index' => '2',
                    'is_hidden' => '0',
                    'type' => '1',
                    'nav_item_type_id' => '86',
                    'redirect' => false,
                    'module_name' => false,
                    'container' => 'default',
                    'depth' => 2,
            ),
            125 =>
            array(
                    'id' => '125',
                    'nav_id' => '50',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/a-notre-sujet/prestation-propre',
                    'title' => 'Prestation propre',
                    'alias' => 'a-notre-sujet/prestation-propre',
                    'description' => 'Finden Sie hier weitere Informationen zu den Eigenleistungen des Vereins.',
                    'keywords' => 'Eigenleistungen, Verein, Recycling-Sack, Recycling, Sack',
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483355408',
                    'timestamp_update' => '1483358914',
                    'is_home' => '0',
                    'parent_nav_id' => '13',
                    'sort_index' => '3',
                    'is_hidden' => '0',
                    'type' => '1',
                    'nav_item_type_id' => '87',
                    'redirect' => false,
                    'module_name' => false,
                    'container' => 'default',
                    'depth' => 2,
            ),
            126 =>
            array(
                    'id' => '126',
                    'nav_id' => '16',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/a-notre-sujet/histoire',
                    'title' => 'Histoire',
                    'alias' => 'a-notre-sujet/histoire',
                    'description' => 'Die Geschichte des Vereins «IG Recycling-Sack»',
                    'keywords' => 'Geschichte, IG, Interessengemeinschaft, Verein, Recycling-Sack, Sack, Recycling, Verein',
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483358934',
                    'timestamp_update' => '1483359085',
                    'is_home' => '0',
                    'parent_nav_id' => '13',
                    'sort_index' => '5',
                    'is_hidden' => '0',
                    'type' => '1',
                    'nav_item_type_id' => '88',
                    'redirect' => false,
                    'module_name' => false,
                    'container' => 'default',
                    'depth' => 2,
            ),
            127 =>
            array(
                    'id' => '127',
                    'nav_id' => '17',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/a-notre-sujet/philosophie',
                    'title' => 'Philosophie',
                    'alias' => 'a-notre-sujet/philosophie',
                    'description' => 'Erfahren Sie hier mehr über Merkmale und Zweck des Vereins «IG Recycling-Sack»',
                    'keywords' => 'Merkmal, Zweck, IG, Interessengemeinschaft, Recycling, Recycling-Sack, Sack, Verein, Philosophie',
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483359101',
                    'timestamp_update' => '1483359413',
                    'is_home' => '0',
                    'parent_nav_id' => '13',
                    'sort_index' => '6',
                    'is_hidden' => '0',
                    'type' => '1',
                    'nav_item_type_id' => '89',
                    'redirect' => false,
                    'module_name' => false,
                    'container' => 'default',
                    'depth' => 2,
            ),
            128 =>
            array(
                    'id' => '128',
                    'nav_id' => '89',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/a-notre-sujet/sabonner-a-la-newsletter',
                    'title' => 'S’abonner à la newsletter',
                    'alias' => 'a-notre-sujet/sabonner-a-la-newsletter',
                    'description' => null,
                    'keywords' => null,
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483359459',
                    'timestamp_update' => '1483359635',
                    'is_home' => '0',
                    'parent_nav_id' => '13',
                    'sort_index' => '8',
                    'is_hidden' => '0',
                    'type' => '1',
                    'nav_item_type_id' => '90',
                    'redirect' => false,
                    'module_name' => false,
                    'container' => 'default',
                    'depth' => 2,
            ),
            113 =>
            array(
                    'id' => '113',
                    'nav_id' => '49',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/partenaires-de-collecte-de-logistique/services-pour-la-collecte-et-la-logistique',
                    'title' => 'Services pour la collecte et la logistique',
                    'alias' => 'partenaires-de-collecte-de-logistique/services-pour-la-collecte-et-la-logistique',
                    'description' => 'In Zusammenarbeit mit dem Verein IG Recycling-Sack erbringen die Sammel- und Logistikpartner verschiedenste Dienstleistungen. Hier erfahren Sie weitere Informationen dazu.',
                    'keywords' => 'Zusammenarbeit, Recycling-Sack, Recycling, Sack, Verein, IG, Interessengemeinschaft, Dienstleistungen, Logistikparter, Logistik, Sammelpartner, Sammeln',
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483347741',
                    'timestamp_update' => '1483355736',
                    'is_home' => '0',
                    'parent_nav_id' => '22',
                    'sort_index' => '1',
                    'is_hidden' => '0',
                    'type' => '1',
                    'nav_item_type_id' => '75',
                    'redirect' => false,
                    'module_name' => false,
                    'container' => 'default',
                    'depth' => 2,
            ),
            114 =>
            array(
                    'id' => '114',
                    'nav_id' => '82',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/partenaires-de-collecte-de-logistique/financement-du-systeme',
                    'title' => 'Financement du système',
                    'alias' => 'partenaires-de-collecte-de-logistique/financement-du-systeme',
                    'description' => 'Finanzierung, System, Recycling, Sack, Kunststoff, Sammlung',
                    'keywords' => '',
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483349254',
                    'timestamp_update' => '1483349759',
                    'is_home' => '0',
                    'parent_nav_id' => '22',
                    'sort_index' => '2',
                    'is_hidden' => '0',
                    'type' => '1',
                    'nav_item_type_id' => '76',
                    'redirect' => false,
                    'module_name' => false,
                    'container' => 'default',
                    'depth' => 2,
            ),
            115 =>
            array(
                    'id' => '115',
                    'nav_id' => '51',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/partenaires-de-collecte-de-logistique/avantages-du-systeme',
                    'title' => 'Avantages du système',
                    'alias' => 'partenaires-de-collecte-de-logistique/avantages-du-systeme',
                    'description' => 'Das «Recycling-Sack»-System bietet für die Sammel- und Logistikpartner einige Vorteile. Hier erfahren Sie die wichtigsten allgemeinen Vorteile.',
                    'keywords' => 'Vorteile, Recycling, Sack, Recycling-Sack, allgemein',
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483349806',
                    'timestamp_update' => '1483350553',
                    'is_home' => '0',
                    'parent_nav_id' => '22',
                    'sort_index' => '3',
                    'is_hidden' => '0',
                    'type' => '1',
                    'nav_item_type_id' => '77',
                    'redirect' => false,
                    'module_name' => false,
                    'container' => 'default',
                    'depth' => 2,
            ),
            116 =>
            array(
                    'id' => '116',
                    'nav_id' => '48',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/partenaires-de-collecte-de-logistique/pour-les-associations-de-gestion-de-dechets',
                    'title' => 'Pour les associations de gestion de déchets',
                    'alias' => 'partenaires-de-collecte-de-logistique/pour-les-associations-de-gestion-de-dechets',
                    'description' => 'Hier finden Zweckverbände wichtige Informationen zum «Recycling-Sack».',
                    'keywords' => 'Recycling-Sack, Recycling, Sack, Zweckverbände, Informationen, sammeln',
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483351475',
                    'timestamp_update' => '1483352438',
                    'is_home' => '0',
                    'parent_nav_id' => '22',
                    'sort_index' => '4',
                    'is_hidden' => '0',
                    'type' => '1',
                    'nav_item_type_id' => '78',
                    'redirect' => false,
                    'module_name' => false,
                    'container' => 'default',
                    'depth' => 2,
            ),
            117 =>
            array(
                    'id' => '117',
                    'nav_id' => '39',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/partenaires-de-collecte-de-logistique/pour-les-communes-et-les-villes',
                    'title' => 'Pour les communes et les villes',
                    'alias' => 'partenaires-de-collecte-de-logistique/pour-les-communes-et-les-villes',
                    'description' => 'Hier finden Gemeinden und Städte wichtige Informationen zum «Recycling-Sack».',
                    'keywords' => 'Recycling-Sack, Recycling, Sack, Gemeinde, Stadt, Informationen, sammeln',
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483352467',
                    'timestamp_update' => '1483352685',
                    'is_home' => '0',
                    'parent_nav_id' => '22',
                    'sort_index' => '5',
                    'is_hidden' => '0',
                    'type' => '1',
                    'nav_item_type_id' => '79',
                    'redirect' => false,
                    'module_name' => false,
                    'container' => 'default',
                    'depth' => 2,
            ),
            118 =>
            array(
                    'id' => '118',
                    'nav_id' => '23',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/partenaires-de-collecte-de-logistique/pour-le-partenaire-delimination',
                    'title' => 'Pour le partenaire d’élimination',
                    'alias' => 'partenaires-de-collecte-de-logistique/pour-le-partenaire-delimination',
                    'description' => 'Hier finden Entsorger wichtige Informationen zum «Recycling-Sack».',
                    'keywords' => 'Recycling-Sack, Recycling, Sack, Entsorger, Informationen, sammeln',
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483352712',
                    'timestamp_update' => '1483353028',
                    'is_home' => '0',
                    'parent_nav_id' => '22',
                    'sort_index' => '6',
                    'is_hidden' => '0',
                    'type' => '1',
                    'nav_item_type_id' => '80',
                    'redirect' => false,
                    'module_name' => false,
                    'container' => 'default',
                    'depth' => 2,
            ),
            120 =>
            array(
                    'id' => '120',
                    'nav_id' => '25',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/savoir/le-cadre-du-recyclage',
                    'title' => 'Le cadre du recyclage',
                    'alias' => 'savoir/le-cadre-du-recyclage',
                    'description' => 'Bekommen Sie hier einen Einblick in das Umfeld, in welchem sich der «Recycling-Sack» bewegt.',
                    'keywords' => 'Umfeld, Recycling, Sack, Recycling-Sack',
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483353256',
                    'timestamp_update' => '1483355593',
                    'is_home' => '0',
                    'parent_nav_id' => '24',
                    'sort_index' => '1',
                    'is_hidden' => '0',
                    'type' => '1',
                    'nav_item_type_id' => '82',
                    'redirect' => false,
                    'module_name' => false,
                    'container' => 'default',
                    'depth' => 2,
            ),
            121 =>
            array(
                    'id' => '121',
                    'nav_id' => '33',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/savoir/telechargement',
                    'title' => 'Téléchargement',
                    'alias' => 'savoir/telechargement',
                    'description' => 'Hier finden Sie einige Dateien zum Downloaden: Kommunikationsmittel wie Flyer oder Beschilderungen',
                    'keywords' => 'Download, Kommunikation, Kommunikationsmittel, Flyer, Schreiben, Begleitschreiben, Beschriftung, Sammelstelle, Recycling-Sack, Recycling, Sack, Beschilderung, Grafik',
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483354275',
                    'timestamp_update' => '1483354578',
                    'is_home' => '0',
                    'parent_nav_id' => '24',
                    'sort_index' => '9',
                    'is_hidden' => '0',
                    'type' => '1',
                    'nav_item_type_id' => '83',
                    'redirect' => false,
                    'module_name' => false,
                    'container' => 'default',
                    'depth' => 2,
            ),
            130 =>
            array(
                    'id' => '130',
                    'nav_id' => '54',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/footer-produit',
                    'title' => 'Produit',
                    'alias' => 'footer-produit',
                    'description' => null,
                    'keywords' => null,
                    'create_user_id' => '5',
                    'update_user_id' => '5',
                    'timestamp_create' => '1483368262',
                    'timestamp_update' => '0',
                    'is_home' => '0',
                    'parent_nav_id' => '0',
                    'sort_index' => '1',
                    'is_hidden' => '0',
                    'type' => '3',
                    'nav_item_type_id' => '36',
                    'redirect' =>
                    array(
                            'id' => '36',
                            'type' => '1',
                            'value' => '2',
                    ),
                    'module_name' => false,
                    'container' => 'footer-column-one',
                    'depth' => 1,
            ),
            136 =>
            array(
                    'id' => '136',
                    'nav_id' => '60',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/footer-savoir',
                    'title' => 'Savoir',
                    'alias' => 'footer-savoir',
                    'description' => null,
                    'keywords' => null,
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483370157',
                    'timestamp_update' => '0',
                    'is_home' => '0',
                    'parent_nav_id' => '0',
                    'sort_index' => '2',
                    'is_hidden' => '0',
                    'type' => '3',
                    'nav_item_type_id' => '42',
                    'redirect' => false,
                    'module_name' => false,
                    'container' => 'footer-column-one',
                    'depth' => 1,
            ),
            131 =>
            array(
                    'id' => '131',
                    'nav_id' => '56',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/footer-produit/footer-comment-collecter',
                    'title' => 'Comment collecter?',
                    'alias' => 'footer-produit/footer-comment-collecter',
                    'description' => null,
                    'keywords' => null,
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483369929',
                    'timestamp_update' => '0',
                    'is_home' => '0',
                    'parent_nav_id' => '54',
                    'sort_index' => '2',
                    'is_hidden' => '0',
                    'type' => '3',
                    'nav_item_type_id' => '37',
                    'redirect' =>
                    array(
                            'id' => '37',
                            'type' => '1',
                            'value' => '44',
                    ),
                    'module_name' => false,
                    'container' => 'footer-column-one',
                    'depth' => 2,
            ),
            132 =>
            array(
                    'id' => '132',
                    'nav_id' => '57',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/footer-produit/footer-pourquoi-collecter',
                    'title' => 'Pourquoi collecter?',
                    'alias' => 'footer-produit/footer-pourquoi-collecter',
                    'description' => null,
                    'keywords' => null,
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483369990',
                    'timestamp_update' => '0',
                    'is_home' => '0',
                    'parent_nav_id' => '54',
                    'sort_index' => '3',
                    'is_hidden' => '0',
                    'type' => '3',
                    'nav_item_type_id' => '38',
                    'redirect' =>
                    array(
                            'id' => '38',
                            'type' => '1',
                            'value' => '46',
                    ),
                    'module_name' => false,
                    'container' => 'footer-column-one',
                    'depth' => 2,
            ),
            133 =>
            array(
                    'id' => '133',
                    'nav_id' => '58',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/footer-produit/footer-ou-vente-et-depot',
                    'title' => 'Où? Vente et dépôt',
                    'alias' => 'footer-produit/footer-ou-vente-et-depot',
                    'description' => null,
                    'keywords' => null,
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483370034',
                    'timestamp_update' => '0',
                    'is_home' => '0',
                    'parent_nav_id' => '54',
                    'sort_index' => '4',
                    'is_hidden' => '0',
                    'type' => '3',
                    'nav_item_type_id' => '39',
                    'redirect' =>
                    array(
                            'id' => '39',
                            'type' => '1',
                            'value' => '45',
                    ),
                    'module_name' => false,
                    'container' => 'footer-column-one',
                    'depth' => 2,
            ),
            134 =>
            array(
                    'id' => '134',
                    'nav_id' => '92',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/footer-produit/footer-la-differance-avec-des-collectes-de-plastiques-melanges',
                    'title' => 'La differance avec des collectes de plastiques mélangés',
                    'alias' => 'footer-produit/footer-la-differance-avec-des-collectes-de-plastiques-melanges',
                    'description' => null,
                    'keywords' => null,
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483370075',
                    'timestamp_update' => '0',
                    'is_home' => '0',
                    'parent_nav_id' => '54',
                    'sort_index' => '7',
                    'is_hidden' => '0',
                    'type' => '3',
                    'nav_item_type_id' => '40',
                    'redirect' =>
                    array(
                            'id' => '40',
                            'type' => '1',
                            'value' => '91',
                    ),
                    'module_name' => false,
                    'container' => 'footer-column-one',
                    'depth' => 2,
            ),
            135 =>
            array(
                    'id' => '135',
                    'nav_id' => '59',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/footer-produit/footer-faq-questions-frequentes',
                    'title' => 'FAQ – Questions fréquentes',
                    'alias' => 'footer-produit/footer-faq-questions-frequentes',
                    'description' => null,
                    'keywords' => null,
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483370106',
                    'timestamp_update' => '0',
                    'is_home' => '0',
                    'parent_nav_id' => '54',
                    'sort_index' => '8',
                    'is_hidden' => '0',
                    'type' => '3',
                    'nav_item_type_id' => '41',
                    'redirect' =>
                    array(
                            'id' => '41',
                            'type' => '1',
                            'value' => '34',
                    ),
                    'module_name' => false,
                    'container' => 'footer-column-one',
                    'depth' => 2,
            ),
            137 =>
            array(
                    'id' => '137',
                    'nav_id' => '61',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/footer-savoir/footer-le-cadre-du-recyclage',
                    'title' => 'Le cadre du recyclage',
                    'alias' => 'footer-savoir/footer-le-cadre-du-recyclage',
                    'description' => null,
                    'keywords' => null,
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483370193',
                    'timestamp_update' => '0',
                    'is_home' => '0',
                    'parent_nav_id' => '60',
                    'sort_index' => '1',
                    'is_hidden' => '0',
                    'type' => '3',
                    'nav_item_type_id' => '43',
                    'redirect' =>
                    array(
                            'id' => '43',
                            'type' => '1',
                            'value' => '25',
                    ),
                    'module_name' => false,
                    'container' => 'footer-column-one',
                    'depth' => 2,
            ),
            138 =>
            array(
                    'id' => '138',
                    'nav_id' => '62',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/footer-savoir/footer-telechargement',
                    'title' => 'Téléchargement',
                    'alias' => 'footer-savoir/footer-telechargement',
                    'description' => null,
                    'keywords' => null,
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483370223',
                    'timestamp_update' => '0',
                    'is_home' => '0',
                    'parent_nav_id' => '60',
                    'sort_index' => '2',
                    'is_hidden' => '0',
                    'type' => '3',
                    'nav_item_type_id' => '44',
                    'redirect' =>
                    array(
                            'id' => '44',
                            'type' => '1',
                            'value' => '33',
                    ),
                    'module_name' => false,
                    'container' => 'footer-column-one',
                    'depth' => 2,
            ),
            147 =>
            array(
                    'id' => '147',
                    'nav_id' => '74',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/footer-partenaires-de-collecte-de-logistique',
                    'title' => 'Partenaires de collecte / de logistique',
                    'alias' => 'footer-partenaires-de-collecte-de-logistique',
                    'description' => null,
                    'keywords' => null,
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483370717',
                    'timestamp_update' => '0',
                    'is_home' => '0',
                    'parent_nav_id' => '0',
                    'sort_index' => '1',
                    'is_hidden' => '0',
                    'type' => '3',
                    'nav_item_type_id' => '53',
                    'redirect' =>
                    array(
                            'id' => '53',
                            'type' => '1',
                            'value' => '74',
                    ),
                    'module_name' => false,
                    'container' => 'footer-column-three',
                    'depth' => 1,
            ),
            148 =>
            array(
                    'id' => '148',
                    'nav_id' => '75',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/footer-partenaires-de-collecte-de-logistique/footer-services-pour-la-collecte-et-la-logistique',
                    'title' => 'Services pour la collecte et la logistique',
                    'alias' => 'footer-partenaires-de-collecte-de-logistique/footer-services-pour-la-collecte-et-la-logistique',
                    'description' => null,
                    'keywords' => null,
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483372752',
                    'timestamp_update' => '0',
                    'is_home' => '0',
                    'parent_nav_id' => '74',
                    'sort_index' => '1',
                    'is_hidden' => '0',
                    'type' => '3',
                    'nav_item_type_id' => '54',
                    'redirect' =>
                    array(
                            'id' => '54',
                            'type' => '1',
                            'value' => '49',
                    ),
                    'module_name' => false,
                    'container' => 'footer-column-three',
                    'depth' => 2,
            ),
            149 =>
            array(
                    'id' => '149',
                    'nav_id' => '83',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/footer-partenaires-de-collecte-de-logistique/footer-financement-du-systeme',
                    'title' => 'Financement du système',
                    'alias' => 'footer-partenaires-de-collecte-de-logistique/footer-financement-du-systeme',
                    'description' => null,
                    'keywords' => null,
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483372801',
                    'timestamp_update' => '0',
                    'is_home' => '0',
                    'parent_nav_id' => '74',
                    'sort_index' => '2',
                    'is_hidden' => '0',
                    'type' => '3',
                    'nav_item_type_id' => '55',
                    'redirect' =>
                    array(
                            'id' => '55',
                            'type' => '1',
                            'value' => '82',
                    ),
                    'module_name' => false,
                    'container' => 'footer-column-three',
                    'depth' => 2,
            ),
            150 =>
            array(
                    'id' => '150',
                    'nav_id' => '76',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/footer-partenaires-de-collecte-de-logistique/footer-avantages-du-systeme',
                    'title' => 'Avantages du système',
                    'alias' => 'footer-partenaires-de-collecte-de-logistique/footer-avantages-du-systeme',
                    'description' => null,
                    'keywords' => null,
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483372862',
                    'timestamp_update' => '0',
                    'is_home' => '0',
                    'parent_nav_id' => '74',
                    'sort_index' => '3',
                    'is_hidden' => '0',
                    'type' => '3',
                    'nav_item_type_id' => '56',
                    'redirect' =>
                    array(
                            'id' => '56',
                            'type' => '1',
                            'value' => '51',
                    ),
                    'module_name' => false,
                    'container' => 'footer-column-three',
                    'depth' => 2,
            ),
            151 =>
            array(
                    'id' => '151',
                    'nav_id' => '77',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/footer-partenaires-de-collecte-de-logistique/footer-pour-les-associations-de-gestion-de-dechets',
                    'title' => 'Pour les associations de gestion de déchets',
                    'alias' => 'footer-partenaires-de-collecte-de-logistique/footer-pour-les-associations-de-gestion-de-dechets',
                    'description' => null,
                    'keywords' => null,
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483372929',
                    'timestamp_update' => '0',
                    'is_home' => '0',
                    'parent_nav_id' => '74',
                    'sort_index' => '4',
                    'is_hidden' => '0',
                    'type' => '3',
                    'nav_item_type_id' => '57',
                    'redirect' =>
                    array(
                            'id' => '57',
                            'type' => '1',
                            'value' => '48',
                    ),
                    'module_name' => false,
                    'container' => 'footer-column-three',
                    'depth' => 2,
            ),
            153 =>
            array(
                    'id' => '153',
                    'nav_id' => '79',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/footer-partenaires-de-collecte-de-logistique/footer-pour-le-partenaire-delimination',
                    'title' => 'Pour le partenaire d’élimination',
                    'alias' => 'footer-partenaires-de-collecte-de-logistique/footer-pour-le-partenaire-delimination',
                    'description' => null,
                    'keywords' => null,
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483373050',
                    'timestamp_update' => '0',
                    'is_home' => '0',
                    'parent_nav_id' => '74',
                    'sort_index' => '6',
                    'is_hidden' => '0',
                    'type' => '3',
                    'nav_item_type_id' => '59',
                    'redirect' =>
                    array(
                            'id' => '59',
                            'type' => '1',
                            'value' => '23',
                    ),
                    'module_name' => false,
                    'container' => 'footer-column-three',
                    'depth' => 2,
            ),
            139 =>
            array(
                    'id' => '139',
                    'nav_id' => '65',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/footer-carte',
                    'title' => 'Carte',
                    'alias' => 'footer-carte',
                    'description' => null,
                    'keywords' => null,
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483370270',
                    'timestamp_update' => '0',
                    'is_home' => '0',
                    'parent_nav_id' => '0',
                    'sort_index' => '1',
                    'is_hidden' => '0',
                    'type' => '3',
                    'nav_item_type_id' => '45',
                    'redirect' =>
                    array(
                            'id' => '45',
                            'type' => '1',
                            'value' => '6',
                    ),
                    'module_name' => false,
                    'container' => 'footer-column-two',
                    'depth' => 1,
            ),
            140 =>
            array(
                    'id' => '140',
                    'nav_id' => '66',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/footer-a-notre-sujet',
                    'title' => 'A notre sujet',
                    'alias' => 'footer-a-notre-sujet',
                    'description' => null,
                    'keywords' => null,
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483370313',
                    'timestamp_update' => '0',
                    'is_home' => '0',
                    'parent_nav_id' => '0',
                    'sort_index' => '2',
                    'is_hidden' => '0',
                    'type' => '3',
                    'nav_item_type_id' => '46',
                    'redirect' =>
                    array(
                            'id' => '46',
                            'type' => '1',
                            'value' => '13',
                    ),
                    'module_name' => false,
                    'container' => 'footer-column-two',
                    'depth' => 1,
            ),
            146 =>
            array(
                    'id' => '146',
                    'nav_id' => '72',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/footer-processus-de-recyclage',
                    'title' => 'Processus de recyclage',
                    'alias' => 'footer-processus-de-recyclage',
                    'description' => null,
                    'keywords' => null,
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483370610',
                    'timestamp_update' => '0',
                    'is_home' => '0',
                    'parent_nav_id' => '0',
                    'sort_index' => '3',
                    'is_hidden' => '0',
                    'type' => '3',
                    'nav_item_type_id' => '52',
                    'redirect' =>
                    array(
                            'id' => '52',
                            'type' => '1',
                            'value' => '40',
                    ),
                    'module_name' => false,
                    'container' => 'footer-column-two',
                    'depth' => 1,
            ),
            141 =>
            array(
                    'id' => '141',
                    'nav_id' => '67',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/footer-a-notre-sujet/footer-contact',
                    'title' => 'Contact',
                    'alias' => 'footer-a-notre-sujet/footer-contact',
                    'description' => null,
                    'keywords' => null,
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483370356',
                    'timestamp_update' => '0',
                    'is_home' => '0',
                    'parent_nav_id' => '66',
                    'sort_index' => '1',
                    'is_hidden' => '0',
                    'type' => '3',
                    'nav_item_type_id' => '47',
                    'redirect' =>
                    array(
                            'id' => '47',
                            'type' => '1',
                            'value' => '14',
                    ),
                    'module_name' => false,
                    'container' => 'footer-column-two',
                    'depth' => 2,
            ),
            142 =>
            array(
                    'id' => '142',
                    'nav_id' => '68',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/footer-a-notre-sujet/footer-lassociation',
                    'title' => 'L’association',
                    'alias' => 'footer-a-notre-sujet/footer-lassociation',
                    'description' => null,
                    'keywords' => null,
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483370395',
                    'timestamp_update' => '0',
                    'is_home' => '0',
                    'parent_nav_id' => '66',
                    'sort_index' => '2',
                    'is_hidden' => '0',
                    'type' => '3',
                    'nav_item_type_id' => '48',
                    'redirect' =>
                    array(
                            'id' => '48',
                            'type' => '1',
                            'value' => '68',
                    ),
                    'module_name' => false,
                    'container' => 'footer-column-two',
                    'depth' => 2,
            ),
            143 =>
            array(
                    'id' => '143',
                    'nav_id' => '69',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/footer-a-notre-sujet/footer-prestation-propre',
                    'title' => 'Prestation propre',
                    'alias' => 'footer-a-notre-sujet/footer-prestation-propre',
                    'description' => null,
                    'keywords' => null,
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483370434',
                    'timestamp_update' => '0',
                    'is_home' => '0',
                    'parent_nav_id' => '66',
                    'sort_index' => '3',
                    'is_hidden' => '0',
                    'type' => '3',
                    'nav_item_type_id' => '49',
                    'redirect' =>
                    array(
                            'id' => '49',
                            'type' => '1',
                            'value' => '69',
                    ),
                    'module_name' => false,
                    'container' => 'footer-column-two',
                    'depth' => 2,
            ),
            144 =>
            array(
                    'id' => '144',
                    'nav_id' => '70',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/footer-a-notre-sujet/footer-histoire',
                    'title' => 'Histoire',
                    'alias' => 'footer-a-notre-sujet/footer-histoire',
                    'description' => null,
                    'keywords' => null,
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483370475',
                    'timestamp_update' => '0',
                    'is_home' => '0',
                    'parent_nav_id' => '66',
                    'sort_index' => '4',
                    'is_hidden' => '0',
                    'type' => '3',
                    'nav_item_type_id' => '50',
                    'redirect' =>
                    array(
                            'id' => '50',
                            'type' => '1',
                            'value' => '16',
                    ),
                    'module_name' => false,
                    'container' => 'footer-column-two',
                    'depth' => 2,
            ),
            145 =>
            array(
                    'id' => '145',
                    'nav_id' => '71',
                    'lang' => 'fr',
                    'link' => '/public_html/fr/footer-a-notre-sujet/footer-philosophie',
                    'title' => 'Philosophie',
                    'alias' => 'footer-a-notre-sujet/footer-philosophie',
                    'description' => null,
                    'keywords' => null,
                    'create_user_id' => '4',
                    'update_user_id' => '4',
                    'timestamp_create' => '1483370530',
                    'timestamp_update' => '0',
                    'is_home' => '0',
                    'parent_nav_id' => '66',
                    'sort_index' => '5',
                    'is_hidden' => '0',
                    'type' => '3',
                    'nav_item_type_id' => '51',
                    'redirect' =>
                    array(
                            'id' => '51',
                            'type' => '1',
                            'value' => '71',
                    ),
                    'module_name' => false,
                    'container' => 'footer-column-two',
                    'depth' => 2,
            ),
    );
